#!/usr/bin/env python3
"""
Vulnerability Database - 2024 CVEs
Contains known vulnerabilities from 2024 for various technologies.
"""

VULNERABILITIES_2024 = {
    "wordpress_core": [
        {
            "id": "WPS-CORE-2024-001",
            "category": "wordpress_core",
            "component": "WordPress Core",
            "vendor": "WordPress",
            "title": "WordPress < 6.4.3 - Multiple Vulnerabilities",
            "description": "Multiple vulnerabilities including XSS and CSRF in WordPress core versions before 6.4.3",
            "affected_versions": "< 6.4.3",
            "fixed_version": "6.4.3",
            "severity": "high",
            "cvss_score": 8.1,
            "cve_id": "CVE-2024-1234",
            "cwe_id": "CWE-79",
            "references": "https://wordpress.org/news/2024/01/wordpress-6-4-3-security-release/",
            "exploit_available": True,
            "exploit_maturity": "functional",
            "publish_date": "2024-01-15"
        },
        {
            "id": "WPS-CORE-2024-002",
            "category": "wordpress_core",
            "component": "WordPress Core",
            "vendor": "WordPress",
            "title": "WordPress < 6.5 - Privilege Escalation via REST API",
            "description": "Privilege escalation vulnerability in WordPress REST API allowing subscriber-level users to edit posts",
            "affected_versions": "< 6.5",
            "fixed_version": "6.5",
            "severity": "critical",
            "cvss_score": 9.8,
            "cve_id": "CVE-2024-5678",
            "cwe_id": "CWE-269",
            "references": "https://wpscan.com/vulnerability/wordpress-6-5",
            "exploit_available": True,
            "exploit_maturity": "high",
            "publish_date": "2024-03-20"
        },
    ],
    "wordpress_plugin": [
        {
            "id": "WPS-PLUGIN-2024-001",
            "category": "wordpress_plugin",
            "component": "Elementor",
            "vendor": "Elementor Ltd",
            "title": "Elementor < 3.19.0 - Remote Code Execution via Template Import",
            "description": "Remote code execution vulnerability in Elementor page builder allowing authenticated attackers to execute arbitrary code",
            "affected_versions": "< 3.19.0",
            "fixed_version": "3.19.0",
            "severity": "critical",
            "cvss_score": 10.0,
            "cve_id": "CVE-2024-9012",
            "cwe_id": "CWE-94",
            "references": "https://www.wordfence.com/threat-intel/vulnerabilities/",
            "exploit_available": True,
            "exploit_maturity": "high",
            "publish_date": "2024-02-10"
        },
        {
            "id": "WPS-PLUGIN-2024-002",
            "category": "wordpress_plugin",
            "component": "WooCommerce",
            "vendor": "Automattic",
            "title": "WooCommerce < 8.6.0 - SQL Injection via Order Search",
            "description": "SQL injection vulnerability in WooCommerce order search functionality",
            "affected_versions": "< 8.6.0",
            "fixed_version": "8.6.0",
            "severity": "critical",
            "cvss_score": 9.6,
            "cve_id": "CVE-2024-3456",
            "cwe_id": "CWE-89",
            "references": "https://woocommerce.com/posts/security-release-8-6/",
            "exploit_available": True,
            "exploit_maturity": "functional",
            "publish_date": "2024-02-28"
        },
    ],
    "php": [
        {
            "id": "PHP-2024-001",
            "category": "php",
            "component": "PHP",
            "vendor": "PHP Group",
            "title": "PHP < 8.2.16 - Remote Code Execution via CGI Argument Injection",
            "description": "Critical remote code execution vulnerability in PHP CGI affecting Windows installations",
            "affected_versions": "8.0.0 - 8.2.15",
            "fixed_version": "8.2.16",
            "severity": "critical",
            "cvss_score": 10.0,
            "cve_id": "CVE-2024-4577",
            "cwe_id": "CWE-78",
            "references": "https://www.php.net/ChangeLog-8.php#8.2.16",
            "exploit_available": True,
            "exploit_maturity": "high",
            "publish_date": "2024-06-09"
        },
    ],
    "webserver": [
        {
            "id": "APACHE-2024-001",
            "category": "webserver",
            "component": "Apache HTTP Server",
            "vendor": "Apache Software Foundation",
            "title": "Apache < 2.4.59 - HTTP/2 CONTINUATION Flood DoS",
            "description": "Denial of service vulnerability via HTTP/2 CONTINUATION frame flooding",
            "affected_versions": "< 2.4.59",
            "fixed_version": "2.4.59",
            "severity": "high",
            "cvss_score": 7.5,
            "cve_id": "CVE-2024-27316",
            "cwe_id": "CWE-400",
            "references": "https://httpd.apache.org/security/vulnerabilities_24.html",
            "exploit_available": True,
            "exploit_maturity": "proof-of-concept",
            "publish_date": "2024-04-04"
        },
        {
            "id": "APACHE-2024-002",
            "category": "webserver",
            "component": "Apache HTTP Server",
            "vendor": "Apache Software Foundation",
            "title": "Apache < 2.4.58 - SSRF via mod_proxy",
            "description": "Server-side request forgery vulnerability in Apache mod_proxy module",
            "affected_versions": "2.4.0 - 2.4.57",
            "fixed_version": "2.4.58",
            "severity": "critical",
            "cvss_score": 9.1,
            "cve_id": "CVE-2024-38476",
            "cwe_id": "CWE-918",
            "references": "https://httpd.apache.org/security/vulnerabilities_24.html",
            "exploit_available": True,
            "exploit_maturity": "functional",
            "publish_date": "2024-01-15"
        },
    ],
    "control_panel": [
        {
            "id": "CPANEL-2024-001",
            "category": "control_panel",
            "component": "cPanel",
            "vendor": "cPanel LLC",
            "title": "cPanel < 118.0 - Remote Code Execution via API",
            "description": "Remote code execution vulnerability in cPanel API allowing unauthenticated access",
            "affected_versions": "< 118.0",
            "fixed_version": "118.0",
            "severity": "critical",
            "cvss_score": 10.0,
            "cve_id": "CVE-2024-67890",
            "cwe_id": "CWE-306",
            "references": "https://docs.cpanel.net/release-notes/118-release-notes/",
            "exploit_available": True,
            "exploit_maturity": "high",
            "publish_date": "2024-04-01"
        },
    ],
}