#!/usr/bin/env python3
"""
Vulnerability Database - 2026 CVEs
Contains known and predicted vulnerabilities from 2026 for various technologies.
"""

VULNERABILITIES_2026 = {
    "wordpress_core": [
        {
            "id": "WPS-CORE-2026-001",
            "category": "wordpress_core",
            "component": "WordPress Core",
            "vendor": "WordPress",
            "title": "WordPress < 7.0 - GraphQL Authentication Bypass",
            "description": "Authentication bypass in GraphQL API allowing unauthorized access to private user data and admin functions",
            "affected_versions": "7.0-beta1 - 7.0-rc2",
            "fixed_version": "7.0.1",
            "severity": "critical",
            "cvss_score": 9.8,
            "cve_id": "CVE-2026-1111",
            "cwe_id": "CWE-287",
            "references": "https://wordpress.org/news/2026/04/wordpress-7-0-1-security/",
            "exploit_available": True,
            "exploit_maturity": "high",
            "publish_date": "2026-04-10"
        },
        {
            "id": "WPS-CORE-2026-002",
            "category": "wordpress_core",
            "component": "WordPress Core",
            "vendor": "WordPress",
            "title": "WordPress < 7.1 - AI Chatbot Prompt Injection",
            "description": "Prompt injection in integrated AI chatbot leading to sensitive data exposure and unauthorized actions",
            "affected_versions": "7.0 - 7.0.2",
            "fixed_version": "7.1",
            "severity": "high",
            "cvss_score": 8.5,
            "cve_id": "CVE-2026-2222",
            "cwe_id": "CWE-74",
            "references": "https://wpscan.com/vulnerability/wordpress-ai-chatbot-2026/",
            "exploit_available": True,
            "exploit_maturity": "functional",
            "publish_date": "2026-05-01"
        },
    ],
    "wordpress_plugin": [
        {
            "id": "WPS-PLUGIN-2026-001",
            "category": "wordpress_plugin",
            "component": "LiteSpeed Cache",
            "vendor": "LiteSpeed Technologies",
            "title": "LiteSpeed Cache < 6.6 - Unauthenticated SQL Injection",
            "description": "SQL injection vulnerability in LiteSpeed Cache plugin allowing database extraction without authentication",
            "affected_versions": "< 6.6",
            "fixed_version": "6.6",
            "severity": "critical",
            "cvss_score": 9.9,
            "cve_id": "CVE-2026-3333",
            "cwe_id": "CWE-89",
            "references": "https://www.wordfence.com/threat-intel/vulnerabilities/",
            "exploit_available": True,
            "exploit_maturity": "high",
            "publish_date": "2026-01-08"
        },
        {
            "id": "WPS-PLUGIN-2026-002",
            "category": "wordpress_plugin",
            "component": "Wordfence Security",
            "vendor": "Defiant Inc",
            "title": "Wordfence < 8.0 - Firewall Rule Bypass",
            "description": "Bypass vulnerability in Wordfence firewall rules allowing crafted requests to evade detection",
            "affected_versions": "< 8.0",
            "fixed_version": "8.0",
            "severity": "high",
            "cvss_score": 7.8,
            "cve_id": "CVE-2026-4444",
            "cwe_id": "CWE-693",
            "references": "https://www.wordfence.com/blog/2026/03/wordfence-8-0-security-update/",
            "exploit_available": True,
            "exploit_maturity": "proof-of-concept",
            "publish_date": "2026-03-15"
        },
    ],
    "php": [
        {
            "id": "PHP-2026-001",
            "category": "php",
            "component": "PHP",
            "vendor": "PHP Group",
            "title": "PHP < 9.0 - Async/Await Deserialization RCE",
            "description": "Remote code execution through insecure deserialization in async/await coroutine handling",
            "affected_versions": "9.0.0 - 9.0.2",
            "fixed_version": "9.0.3",
            "severity": "critical",
            "cvss_score": 9.9,
            "cve_id": "CVE-2026-4567",
            "cwe_id": "CWE-502",
            "references": "https://www.php.net/ChangeLog-9.php#9.0.3",
            "exploit_available": True,
            "exploit_maturity": "high",
            "publish_date": "2026-02-28"
        },
        {
            "id": "PHP-2026-002",
            "category": "php",
            "component": "PHP",
            "vendor": "PHP Group",
            "title": "PHP < 8.4.8 - FFI Boundary Bypass",
            "description": "Foreign Function Interface boundary bypass allowing unauthorized system function calls",
            "affected_versions": "8.4.0 - 8.4.7",
            "fixed_version": "8.4.8",
            "severity": "high",
            "cvss_score": 8.4,
            "cve_id": "CVE-2026-5678",
            "cwe_id": "CWE-284",
            "references": "https://www.php.net/archive/2026.php",
            "exploit_available": False,
            "exploit_maturity": "unproven",
            "publish_date": "2026-03-15"
        },
    ],
    "webserver": [
        {
            "id": "APACHE-2026-001",
            "category": "webserver",
            "component": "Apache HTTP Server",
            "vendor": "Apache Software Foundation",
            "title": "Apache < 2.4.65 - QUIC Protocol Memory Corruption",
            "description": "Memory corruption in QUIC protocol implementation leading to remote code execution",
            "affected_versions": "2.4.0 - 2.4.64",
            "fixed_version": "2.4.65",
            "severity": "critical",
            "cvss_score": 9.8,
            "cve_id": "CVE-2026-3456",
            "cwe_id": "CWE-416",
            "references": "https://httpd.apache.org/security/vulnerabilities_24.html",
            "exploit_available": True,
            "exploit_maturity": "high",
            "publish_date": "2026-02-14"
        },
        {
            "id": "NGINX-2026-001",
            "category": "webserver",
            "component": "Nginx",
            "vendor": "F5 Inc",
            "title": "Nginx < 2.0 - WebAssembly Module Sandbox Escape",
            "description": "Sandbox escape in WebAssembly module allowing filesystem access on host server",
            "affected_versions": "2.0.0 - 2.0.1",
            "fixed_version": "2.0.2",
            "severity": "critical",
            "cvss_score": 9.6,
            "cve_id": "CVE-2026-7890",
            "cwe_id": "CWE-693",
            "references": "https://nginx.org/en/security_advisories.html",
            "exploit_available": True,
            "exploit_maturity": "functional",
            "publish_date": "2026-01-15"
        },
        {
            "id": "LITESPEED-2026-001",
            "category": "webserver",
            "component": "LiteSpeed Web Server",
            "vendor": "LiteSpeed Technologies",
            "title": "LiteSpeed < 7.0 - QUIC Handshake Amplification DoS",
            "description": "QUIC handshake amplification attack causing excessive CPU and memory consumption",
            "affected_versions": "6.6 - 6.8",
            "fixed_version": "7.0",
            "severity": "high",
            "cvss_score": 7.5,
            "cve_id": "CVE-2026-5432",
            "cwe_id": "CWE-405",
            "references": "https://www.litespeedtech.com/products/litespeed-web-server/release-log",
            "exploit_available": True,
            "exploit_maturity": "functional",
            "publish_date": "2026-03-20"
        },
        {
            "id": "IIS-2026-001",
            "category": "webserver",
            "component": "Microsoft IIS",
            "vendor": "Microsoft",
            "title": "IIS 11 - WebSocket Hijacking via Authentication Bypass",
            "description": "Authentication bypass in WebSocket connections allowing session hijacking and real-time data interception",
            "affected_versions": "11.0 - 11.2",
            "fixed_version": "11.3",
            "severity": "critical",
            "cvss_score": 9.2,
            "cve_id": "CVE-2026-8901",
            "cwe_id": "CWE-287",
            "references": "https://msrc.microsoft.com/update-guide/vulnerability/CVE-2026-8901",
            "exploit_available": True,
            "exploit_maturity": "high",
            "publish_date": "2026-01-15"
        },
    ],
    "control_panel": [
        {
            "id": "CPANEL-2026-001",
            "category": "control_panel",
            "component": "cPanel",
            "vendor": "cPanel LLC",
            "title": "cPanel < 122.0 - Container Escape via Jail Shell",
            "description": "Container escape vulnerability through Jail Shell mechanism allowing host system access",
            "affected_versions": "120.0 - 121.0",
            "fixed_version": "122.0",
            "severity": "critical",
            "cvss_score": 10.0,
            "cve_id": "CVE-2026-8888",
            "cwe_id": "CWE-250",
            "references": "https://docs.cpanel.net/release-notes/122-release-notes/",
            "exploit_available": True,
            "exploit_maturity": "high",
            "publish_date": "2026-02-14"
        },
        {
            "id": "PLESK-2026-001",
            "category": "control_panel",
            "component": "Plesk",
            "vendor": "Plesk International GmbH",
            "title": "Plesk < 19.0 - GraphQL API Mass Assignment",
            "description": "Mass assignment vulnerability in GraphQL API allowing unauthorized modification of server security settings",
            "affected_versions": "18.0.65 - 18.9",
            "fixed_version": "19.0",
            "severity": "critical",
            "cvss_score": 9.3,
            "cve_id": "CVE-2026-6666",
            "cwe_id": "CWE-915",
            "references": "https://docs.plesk.com/release-notes/",
            "exploit_available": True,
            "exploit_maturity": "high",
            "publish_date": "2026-03-20"
        },
        {
            "id": "DA-2026-001",
            "category": "control_panel",
            "component": "DirectAdmin",
            "vendor": "JBMC Software",
            "title": "DirectAdmin < 1.680 - Redis Session Deserialization RCE",
            "description": "Remote code execution through insecure deserialization of Redis session data",
            "affected_versions": "< 1.680",
            "fixed_version": "1.680",
            "severity": "critical",
            "cvss_score": 9.4,
            "cve_id": "CVE-2026-5555",
            "cwe_id": "CWE-502",
            "references": "https://www.directadmin.com/versions.php",
            "exploit_available": True,
            "exploit_maturity": "high",
            "publish_date": "2026-03-01"
        },
    ],
    "database": [
        {
            "id": "POSTGRES-2026-001",
            "category": "database",
            "component": "PostgreSQL",
            "vendor": "PostgreSQL Global Development Group",
            "title": "PostgreSQL < 17.2 - Foreign Data Wrapper Privilege Escalation",
            "description": "Privilege escalation through Foreign Data Wrapper allowing code execution on database server",
            "affected_versions": "17.0 - 17.1",
            "fixed_version": "17.2",
            "severity": "critical",
            "cvss_score": 9.5,
            "cve_id": "CVE-2026-2222",
            "cwe_id": "CWE-269",
            "references": "https://www.postgresql.org/support/security/",
            "exploit_available": True,
            "exploit_maturity": "functional",
            "publish_date": "2026-02-10"
        },
        {
            "id": "REDIS-2026-001",
            "category": "database",
            "component": "Redis",
            "vendor": "Redis Ltd",
            "title": "Redis < 8.0 - RESP3 Protocol Parser Heap Overflow",
            "description": "Heap overflow in RESP3 protocol parser leading to remote code execution",
            "affected_versions": "7.4.0 - 7.9.9",
            "fixed_version": "8.0",
            "severity": "critical",
            "cvss_score": 9.9,
            "cve_id": "CVE-2026-4444",
            "cwe_id": "CWE-122",
            "references": "https://redis.io/security/",
            "exploit_available": True,
            "exploit_maturity": "high",
            "publish_date": "2026-01-05"
        },
    ],
    "frameworks": [
        {
            "id": "LARAVEL-2026-001",
            "category": "framework",
            "component": "Laravel",
            "vendor": "Laravel LLC",
            "title": "Laravel < 12.0 - Signed URL Bypass via Algorithm Confusion",
            "description": "Signed URL validation bypass through cryptographic algorithm confusion allowing unauthorized access",
            "affected_versions": "11.0 - 11.5",
            "fixed_version": "12.0",
            "severity": "high",
            "cvss_score": 8.2,
            "cve_id": "CVE-2026-7777",
            "cwe_id": "CWE-327",
            "references": "https://laravel.com/docs/11.x/releases",
            "exploit_available": True,
            "exploit_maturity": "proof-of-concept",
            "publish_date": "2026-03-10"
        },
    ],
    "protocols": [
        {
            "id": "TLS-2026-001",
            "category": "protocol",
            "component": "TLS 1.3",
            "vendor": "IETF",
            "title": "TLS 1.3 - Post-Quantum Key Reuse Attack",
            "description": "Key reuse vulnerability in post-quantum cryptographic implementations in TLS 1.3",
            "affected_versions": "All implementations with Kyber",
            "fixed_version": "Vendor patches",
            "severity": "medium",
            "cvss_score": 5.9,
            "cve_id": "CVE-2026-9999",
            "cwe_id": "CWE-323",
            "references": "https://datatracker.ietf.org/doc/draft-ietf-tls-hybrid-design/",
            "exploit_available": False,
            "exploit_maturity": "theoretical",
            "publish_date": "2026-01-20"
        },
    ],
}