#!/usr/bin/env python3
"""
Vulnerability Database - 2025 CVEs
Contains known vulnerabilities from 2025 for various technologies.
"""

VULNERABILITIES_2025 = {
    "wordpress_core": [
        {
            "id": "WPS-CORE-2025-001",
            "category": "wordpress_core",
            "component": "WordPress Core",
            "vendor": "WordPress",
            "title": "WordPress < 6.7 - AI Content Generator SSRF",
            "description": "Server-Side Request Forgery in AI-powered content generation feature allowing access to internal resources",
            "affected_versions": "< 6.7",
            "fixed_version": "6.7",
            "severity": "high",
            "cvss_score": 8.2,
            "cve_id": "CVE-2025-1234",
            "cwe_id": "CWE-918",
            "references": "https://wordpress.org/news/2025/01/wordpress-6-7-security-release/",
            "exploit_available": True,
            "exploit_maturity": "proof-of-concept",
            "publish_date": "2025-01-15"
        },
        {
            "id": "WPS-CORE-2025-002",
            "category": "wordpress_core",
            "component": "WordPress Core",
            "vendor": "WordPress",
            "title": "WordPress < 6.7.1 - WebAssembly Injection via Block Editor",
            "description": "WebAssembly injection vulnerability in the block editor allowing execution of malicious code in user browsers",
            "affected_versions": "< 6.7.1",
            "fixed_version": "6.7.1",
            "severity": "critical",
            "cvss_score": 9.1,
            "cve_id": "CVE-2025-3456",
            "cwe_id": "CWE-94",
            "references": "https://wpscan.com/vulnerability/wordpress-6-7-1/",
            "exploit_available": True,
            "exploit_maturity": "functional",
            "publish_date": "2025-03-20"
        },
    ],
    "php": [
        {
            "id": "PHP-2025-001",
            "category": "php",
            "component": "PHP",
            "vendor": "PHP Group",
            "title": "PHP < 8.4 - JIT Compiler Buffer Overflow RCE",
            "description": "Remote code execution via buffer overflow in JIT compiler when processing specially crafted scripts",
            "affected_versions": "8.4.0 - 8.4.3",
            "fixed_version": "8.4.4",
            "severity": "critical",
            "cvss_score": 10.0,
            "cve_id": "CVE-2025-7890",
            "cwe_id": "CWE-787",
            "references": "https://www.php.net/ChangeLog-8.php#8.4.4",
            "exploit_available": True,
            "exploit_maturity": "high",
            "publish_date": "2025-02-10"
        },
        {
            "id": "PHP-2025-002",
            "category": "php",
            "component": "PHP",
            "vendor": "PHP Group",
            "title": "PHP < 8.3.15 - Fiber Concurrency Race Condition",
            "description": "Race condition in Fiber concurrency handling leading to memory corruption and potential RCE",
            "affected_versions": "8.1.0 - 8.3.14",
            "fixed_version": "8.3.15",
            "severity": "high",
            "cvss_score": 8.7,
            "cve_id": "CVE-2025-8901",
            "cwe_id": "CWE-362",
            "references": "https://bugs.php.net/bug.php?id=81234",
            "exploit_available": True,
            "exploit_maturity": "proof-of-concept",
            "publish_date": "2025-05-20"
        },
    ],
    "webserver": [
        {
            "id": "APACHE-2025-001",
            "category": "webserver",
            "component": "Apache HTTP Server",
            "vendor": "Apache Software Foundation",
            "title": "Apache < 2.4.62 - HTTP/3 Request Smuggling",
            "description": "HTTP/3 request smuggling vulnerability allowing bypass of security controls and access to backend services",
            "affected_versions": "2.4.0 - 2.4.61",
            "fixed_version": "2.4.62",
            "severity": "critical",
            "cvss_score": 9.4,
            "cve_id": "CVE-2025-9012",
            "cwe_id": "CWE-444",
            "references": "https://httpd.apache.org/security/vulnerabilities_24.html",
            "exploit_available": True,
            "exploit_maturity": "functional",
            "publish_date": "2025-01-20"
        },
        {
            "id": "NGINX-2025-001",
            "category": "webserver",
            "component": "Nginx",
            "vendor": "F5 Inc",
            "title": "Nginx < 1.27.5 - TLS 1.3 0-RTT Replay Attack",
            "description": "TLS 1.3 0-RTT replay vulnerability allowing attackers to replay early data requests",
            "affected_versions": "1.25.0 - 1.27.4",
            "fixed_version": "1.27.5",
            "severity": "high",
            "cvss_score": 7.8,
            "cve_id": "CVE-2025-5678",
            "cwe_id": "CWE-294",
            "references": "https://nginx.org/en/security_advisories.html",
            "exploit_available": True,
            "exploit_maturity": "proof-of-concept",
            "publish_date": "2025-03-10"
        },
        {
            "id": "LITESPEED-2025-001",
            "category": "webserver",
            "component": "LiteSpeed Web Server",
            "vendor": "LiteSpeed Technologies",
            "title": "LiteSpeed < 6.5 - Edge Side Includes Injection",
            "description": "ESI injection vulnerability in LiteSpeed Cache allowing cache poisoning and data exposure",
            "affected_versions": "< 6.5",
            "fixed_version": "6.5",
            "severity": "high",
            "cvss_score": 8.0,
            "cve_id": "CVE-2025-4321",
            "cwe_id": "CWE-74",
            "references": "https://www.litespeedtech.com/products/litespeed-web-server/release-log",
            "exploit_available": True,
            "exploit_maturity": "proof-of-concept",
            "publish_date": "2025-04-01"
        },
        {
            "id": "IIS-2025-001",
            "category": "webserver",
            "component": "Microsoft IIS",
            "vendor": "Microsoft",
            "title": "IIS - HTTP/2 Header Compression Bomb DoS",
            "description": "HTTP/2 HPACK header compression bomb causing denial of service through excessive memory consumption",
            "affected_versions": "8.5 - 10.0",
            "fixed_version": "Patch KB5045678",
            "severity": "high",
            "cvss_score": 7.5,
            "cve_id": "CVE-2025-6789",
            "cwe_id": "CWE-400",
            "references": "https://msrc.microsoft.com/update-guide/vulnerability/CVE-2025-6789",
            "exploit_available": True,
            "exploit_maturity": "proof-of-concept",
            "publish_date": "2025-06-10"
        },
    ],
    "control_panel": [
        {
            "id": "CPANEL-2025-001",
            "category": "control_panel",
            "component": "cPanel",
            "vendor": "cPanel LLC",
            "title": "cPanel < 120.0 - API Token Leakage via Log Files",
            "description": "API token leakage in log files allowing unauthorized access to hosting accounts",
            "affected_versions": "< 120.0",
            "fixed_version": "120.0",
            "severity": "critical",
            "cvss_score": 9.8,
            "cve_id": "CVE-2025-7777",
            "cwe_id": "CWE-532",
            "references": "https://docs.cpanel.net/release-notes/120-release-notes/",
            "exploit_available": True,
            "exploit_maturity": "functional",
            "publish_date": "2025-02-01"
        },
        {
            "id": "PLESK-2025-001",
            "category": "control_panel",
            "component": "Plesk",
            "vendor": "Plesk International GmbH",
            "title": "Plesk < 18.0.65 - Docker API Exposure",
            "description": "Docker API exposure allowing unauthorized container management and potential host compromise",
            "affected_versions": "< 18.0.65",
            "fixed_version": "18.0.65",
            "severity": "critical",
            "cvss_score": 9.6,
            "cve_id": "CVE-2025-3333",
            "cwe_id": "CWE-200",
            "references": "https://docs.plesk.com/release-notes/obsidian/change-log/",
            "exploit_available": True,
            "exploit_maturity": "functional",
            "publish_date": "2025-03-15"
        },
        {
            "id": "DA-2025-001",
            "category": "control_panel",
            "component": "DirectAdmin",
            "vendor": "JBMC Software",
            "title": "DirectAdmin < 1.670 - 2FA Bypass via Token Prediction",
            "description": "Two-factor authentication bypass through time-based token prediction due to weak random seed",
            "affected_versions": "< 1.670",
            "fixed_version": "1.670",
            "severity": "high",
            "cvss_score": 8.1,
            "cve_id": "CVE-2025-4444",
            "cwe_id": "CWE-330",
            "references": "https://www.directadmin.com/versions.php",
            "exploit_available": True,
            "exploit_maturity": "functional",
            "publish_date": "2025-01-25"
        },
    ],
    "database": [
        {
            "id": "MYSQL-2025-001",
            "category": "database",
            "component": "MySQL",
            "vendor": "Oracle",
            "title": "MySQL < 8.4.1 - InnoDB Cluster Authentication Bypass",
            "description": "Authentication bypass in InnoDB Cluster allowing unauthorized node joining and data access",
            "affected_versions": "8.4.0",
            "fixed_version": "8.4.1",
            "severity": "critical",
            "cvss_score": 9.8,
            "cve_id": "CVE-2025-1111",
            "cwe_id": "CWE-287",
            "references": "https://dev.mysql.com/doc/relnotes/mysql/8.4/en/",
            "exploit_available": True,
            "exploit_maturity": "high",
            "publish_date": "2025-01-20"
        },
    ],
}